# Exportarr - Metrics Endpoint (No UI)

services:
  exportarr:
    image: ${EXPORTARR_IMAGE}:${EXPORTARR_TAG}
    env_file:
      - ../.env.defaults
      - ../.env.local
    container_name: exportarr
    cpus: 0.25
    user: ${EXPORTARR_UID}:${MEDIACENTER_GID}
    networks:
      mediacenter:
        ipv4_address: 172.30.0.25
    environment:
    - TZ=${TIMEZONE}
    - PORT=9705
    - URL=http://radarr:7878
    - APIKEY=${RADARR_API_KEY:-}
    - ENABLE_ADDITIONAL_METRICS=true
    ports:
    - ${EXPORTARR_PORT}:9705
    restart: on-failure:5
    logging:
      driver: local
      options:
        max-file: '5'
        max-size: 10m
    labels:
    - traefik.enable=true
    - traefik.http.routers.exportarr.rule=Host(`${EXPORTARR_TRAEFIK_NAME}.${DOMAIN_NAME}`)
    - traefik.http.routers.exportarr.entrypoints=web
    - traefik.http.services.exportarr.loadbalancer.server.port=9705
    depends_on:
      radarr:
        condition: service_healthy
        restart: true
