# Huntarr - Automated Missing Content Discovery

services:
  huntarr:
    image: ${HUNTARR_IMAGE}:${HUNTARR_TAG}
    env_file:
      - ../.env.defaults
      - ../.env.local
    container_name: huntarr
    cpus: 0.5
    user: ${HUNTARR_UID}:${MEDIACENTER_GID}
    networks:
      mediacenter:
        ipv4_address: 172.30.0.23
    environment:
    - PUID=${HUNTARR_UID}
    - PGID=${MEDIACENTER_GID}
    - UMASK=002
    - TZ=${TIMEZONE}
    volumes:
    - ${ROOT_DIR}/config/huntarr-config:/config
    - ${CONFIG}/huntarr-config:/config
    ports:
    - ${HUNTARR_PORT}:9706
    restart: on-failure:5
    logging:
      driver: local
      options:
        max-file: '5'
        max-size: 10m
    labels:
    - traefik.enable=true
    - traefik.http.routers.huntarr.rule=Host(`${HUNTARR_TRAEFIK_NAME}.${DOMAIN_NAME}`)
    - traefik.http.routers.huntarr.entrypoints=web
    - traefik.http.services.huntarr.loadbalancer.server.port=9706
    depends_on:
      prowlarr:
        condition: service_healthy
        restart: true
